# .github/workflows/audit.yml
name: Audit Dependencies

on:
  pull_request:
    branches: [main]
    paths: ['package-lock.json']

jobs:
  audit:
    runs-on: ubuntu-latest
    name: No new vulnerabilities introduced
    steps:
      # STEP 1: Checkout main branch FIRST
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      # STEP 2: Setup Node.js AFTER checkout (so it can find package-lock.json)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (main)
        run: npm ci

      - name: Audit main branch
        run: |
          npm audit --json > audit-main.json || true
          echo "OLD_VULNS=$(jq '.metadata.vulnerabilities.total' audit-main.json)" >> $GITHUB_ENV

      # STEP 3: Checkout PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v4

      # STEP 4: Setup Node.js again for PR branch
      - name: Setup Node.js (PR branch)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (PR)
        run: npm ci

      - name: Audit PR branch
        run: |
          npm audit --json > audit-pr.json || true
          echo "NEW_VULNS=$(jq '.metadata.vulnerabilities.total' audit-pr.json)" >> $GITHUB_ENV

      - name: Compare audit results
        run: |
          echo "Main branch vulnerabilities: $OLD_VULNS"
          echo "PR branch vulnerabilities: $NEW_VULNS"
          if [ "$NEW_VULNS" -gt "$OLD_VULNS" ]; then
            echo "❌ New vulnerabilities introduced!"
            exit 1
          else
            echo "✅ No new vulnerabilities introduced."
          fi
